#!/bin/bash
PROJECT_NAME=''

# stop script on error
set -e

# get parameters
usage() {
  echo "Usage: ${BASH_SOURCE[0]}
    environment: -e <dev|prod>
  " 1>&2
  exit 1
}
while getopts "e:s:n:" o; do
  case "${o}" in
    e)
      ENVIRONMENT=${OPTARG}
      [ "$ENVIRONMENT" == "dev" ] || [ "$ENVIRONMENT" == "prod" ] || usage
      ;;
    *)
      usage
      ;;
esac
done
shift $((OPTIND-1))
if [ -z "${ENVIRONMENT+x}" ]; then
  usage
fi

# get working working directory
cd $(dirname "${BASH_SOURCE[0]}")
project_root_dir="$(pwd)"

# set project name if empty
if [ -z "${PROJECT_NAME+x}" ]; then
  PROJECT_NAME="$(basename "$project_root_dir")"
fi

# get composer if not already downloadeded
if [ ! -f composer.phar ]; then
  wget https://getcomposer.org/composer.phar
fi

if [ "$ENVIRONMENT" == "dev" ]; then

  php composer.phar install

elif [ "$ENVIRONMENT" == "prod" ]; then

  php composer.phar install --no-dev

fi
