#!/bin/bash

set -e

# move to working directory
cd $( dirname "${BASH_SOURCE[0]}" )


# PHP Unit tests

# -v for verbose
if [ "$1" == "-v" ]; then
  ./vendor/bin/phpunit --debug --bootstrap vendor/autoload.php tests
else
  ./vendor/bin/phpunit --testdox --bootstrap vendor/autoload.php tests
fi
